"""Advanced finance work samples: original coding contracts and close/model cases."""
from copy import deepcopy
import json
from pathlib import Path
from app.services.default_assessments import DEFAULT_ASSESSMENTS
from app.services.tax_case_calculations import money
from scripts.build_practical_assessment_banks import document, workpaper_task

ROOT = Path(__file__).resolve().parents[1]
CODING_CONTRACTS = [
 ('reconcile_invoices', 'Invoice and payment reconciliation', 'Aggregate valid payments by invoice_id; reject repeated payment_id; classify matched, underpaid, overpaid and unpaid using Decimal and a 0.01 tolerance. Quarantine malformed and negative records. Sort every output identifier and preserve input objects.', {'invoices':[{'invoice_id':'I1','amount':'100.00'}], 'payments':[{'payment_id':'P1','invoice_id':'I1','amount':'60.00'}]}, {'underpaid':['I1'],'matched':[],'overpaid':[],'unpaid':[],'duplicate_payment_ids':[],'invalid_records':[]}),
 ('allocate_receipts', 'FIFO receipt allocation with disputes', 'Allocate receipts to undisputed open invoices in due_date then invoice_id order within each customer/currency. Partial allocations are allowed; unallocated cash becomes customer credit. Reject duplicate receipt IDs, missing customers, invalid dates and mixed-currency allocation. Round using Decimal, return allocation rows and credit balances.', {'invoices':[{'id':'I1','customer':'C1','currency':'USD','due_date':'2025-01-01','open':'80','disputed':False}], 'receipts':[{'id':'R1','customer':'C1','currency':'USD','amount':'100'}]}, {'allocations':[{'receipt':'R1','invoice':'I1','amount':'80.00'}],'credits':{'C1:USD':'20.00'}}),
 ('detect_duplicate_payables', 'Near-duplicate payable detection', 'Normalize vendor IDs and invoice punctuation/case. Exact normalized vendor/invoice duplicates are blocked. Different invoice IDs with same vendor, currency and amount within three days are review-only. Do not merge credit memos with invoices. Return deterministic blocked groups and review pairs without transitive over-merging.', {'bills':[{'id':'A','vendor':'V1','invoice':'inv-001','currency':'USD','amount':'90','date':'2025-01-01'},{'id':'B','vendor':'V1','invoice':'INV001','currency':'USD','amount':'90','date':'2025-01-02'}]}, {'blocked_groups':[['A','B']],'review_pairs':[]}),
 ('build_aging', 'As-of receivable aging', 'Compute balances as of the policy cutoff, ignoring later payments, reversals and invoices. Apply receipts only once. Bucket positive open amounts into current, 1-30, 31-60, 61-90 and 91-plus using due dates; keep customer credits separately. Validate dates and currencies and emit sorted customer-level totals with reconciliation to the open ledger.', {'as_of':'2025-03-01','invoices':[{'id':'I1','customer':'C','due':'2025-01-01','amount':'100'}],'payments':[]}, {'C':{'current':'0.00','1_30':'0.00','31_60':'100.00','61_90':'0.00','91_plus':'0.00','credit':'0.00'}}),
 ('validate_journals', 'Journal validation and segregation controls', 'Validate every multi-line journal balances in each currency with 0.01 tolerance, uses known active accounts and has one-sided nonnegative lines. Reject repeated journal IDs, invalid period dates and unbalanced entries. Flag creator/approver conflict separately from accounting errors. Report accepted IDs, rejected IDs and reason codes in stable order.', {'accounts':['Cash','Revenue'],'journals':[{'id':'J1','creator':'A','approver':'A','lines':[{'account':'Cash','debit':'100','credit':'0','currency':'USD'},{'account':'Revenue','debit':'0','credit':'100','currency':'USD'}]}]}, {'accepted':['J1'],'rejected':[],'control_flags':{'J1':['creator_is_approver']}}),
 ('recognize_contract_revenue', 'Contract revenue with amendments', 'Allocate fixed consideration to obligations by relative standalone prices, recognize only delivered obligations as of cutoff, and retain deferred revenue. Amendments effective after cutoff are ignored; earlier amendments must not double-count original consideration. Reject missing delivery evidence, duplicate obligation IDs and zero aggregate standalone price. Use cents and assign residual rounding to the last sorted obligation.', {'consideration':'120','obligations':[{'id':'A','standalone':'80','delivered':True},{'id':'B','standalone':'40','delivered':False}]}, {'recognized':'80.00','deferred':'40.00'}),
 ('match_bank_transactions', 'One-to-one bank matching', 'Match bank and ledger records by currency, direction, amount within 0.01 and booking dates within two days. Prefer exact reference matches; never reuse either record. Return unambiguous matches only, ambiguous candidate groups and unmatched IDs. Duplicate source IDs are invalid and must not disappear through dictionary overwrite.', {'bank':[{'id':'B','reference':'R','date':'2025-01-01','currency':'USD','amount':'50'}],'ledger':[{'id':'L','reference':'R','date':'2025-01-02','currency':'USD','amount':'50'}]}, {'matches':[['B','L']],'ambiguous':[],'unmatched_bank':[],'unmatched_ledger':[]}),
 ('compute_cash_waterfall', 'Cash forecast with restricted balances', 'Forecast daily unrestricted cash from opening cash, dated receipts, obligations and minimum-cash policy. Keep restricted cash out of liquidity. Prioritize statutory then critical then discretionary payments within a day and defer insufficient discretionary items. Report deferred IDs and the first breach date, preserving chronological order and avoiding floating-point cents.', {'opening':'100','restricted':'40','minimum':'20','days':[{'date':'2025-01-01','receipt':'0','obligations':[{'id':'P','amount':'90','priority':'discretionary'}]}]}, {'closing':{'2025-01-01':'100.00'},'deferred':['P'],'first_breach':None}),
 ('rollforward_fixed_assets', 'Fixed-asset rollforward', 'Reconcile opening cost and accumulated depreciation with dated additions, disposals and depreciation. Remove disposed asset cost and associated accumulated depreciation once, and compute gain/loss from proceeds less net book value. Reject duplicate disposals, disposal before acquisition and depreciation beyond depreciable cost; show book values by asset and an aggregate rollforward.', {'assets':[{'id':'A','cost':'1000','accumulated':'400'}],'disposals':[{'id':'A','proceeds':'500'}]}, {'closing_cost':'0.00','closing_accumulated':'0.00','gain_loss':'-100.00'}),
 ('evaluate_payment_controls', 'Payment release control engine', 'Release only payments with approved invoices, verified unchanged bank details and independent approvers within the policy limit. Require enhanced approval above the limit and block sanctions flags. Evaluate all reasons rather than stopping at the first. Do not trust a client-provided approved boolean where approval evidence is absent.', {'limit':'1000','payments':[{'id':'P','amount':'500','invoice_approved':True,'bank_verified':False,'creator':'A','approver':'B','sanctions':False}]}, {'released':[],'blocked':{'P':['bank_unverified']}}),
 ('net_intercompany', 'Intercompany netting by currency', 'Net directed obligations separately per currency, preserve zero-sum subsidiary balances and generate a deterministic minimal greedy settlement from sorted creditors/debtors. Reject self-obligations, unknown entities, negative amounts and duplicate obligation IDs. Report balances, settlement rows and invalid IDs; settlements must reproduce original net positions.', {'obligations':[{'id':'O','from':'A','to':'B','currency':'USD','amount':'75'}]}, {'balances':{'USD':{'A':'-75.00','B':'75.00'}},'settlements':[{'from':'A','to':'B','currency':'USD','amount':'75.00'}]}),
 ('translate_trial_balance', 'FX translation and residual control', 'Translate every account at its policy-designated rate class: closing, average or historical. Reject missing rates and duplicate account/currency combinations. Quantize only after conversion, compute translation adjustment as the balancing residual and keep debit/credit signs consistent. Include an audit map of original amounts, rates and translated amounts.', {'accounts':[{'account':'Cash','debit':'100','credit':'0','rate_class':'closing'}],'rates':{'closing':'1.2'}}, {'translated':{'Cash':'120.00'},'balancing_adjustment':'-120.00'}),
 ('reconcile_inventory', 'Inventory quantity and value controls', 'Process purchases, issues and returns chronologically using perpetual weighted-average cost; a return references its original issue cost. Block negative stock and unknown original issues. Round transaction values to cents while maintaining unrounded unit cost internally. Produce quantity, cost, COGS and exception records, and reconcile opening plus movement to closing.', {'opening_qty':10,'opening_cost':'100','movements':[{'id':'M','type':'issue','qty':3}]}, {'closing_qty':7,'closing_cost':'70.00','cogs':'30.00','exceptions':[]}),
 ('amortize_prepaids', 'Daily prepaid expense amortization', 'Compute expense through an as-of date for contracts using inclusive service days, leap-year aware dates and non-overlapping amendments. Cancellation refunds reduce the remaining balance without reopening recognized expense. Prevent duplicate contract IDs and invalid start/end dates. Return recognized expense and prepaid balance per contract and totals.', {'as_of':'2025-01-15','contracts':[{'id':'C','start':'2025-01-01','end':'2025-01-30','cost':'300'}]}, {'C':{'expense':'150.00','prepaid':'150.00'}}),
 ('validate_close_dependencies', 'Close workflow dependency scheduler', 'Find a topological close order using task IDs as tie-breakers. Respect prerequisites, owner availability and blocked tasks. Detect cycles and missing prerequisites explicitly; never return a partial schedule as complete. Return ready tasks, blocked reasons and cycle participants; completed tasks should unlock dependent tasks without being scheduled again.', {'tasks':[{'id':'A','requires':[],'completed':True},{'id':'B','requires':['A'],'completed':False}]}, {'ready':['B'],'blocked':{},'cycles':[]}),
 ('deduplicate_events', 'Idempotent accounting event ingestion', 'Apply events by business sequence rather than arrival order. Exact duplicate event IDs with identical content are ignored; same ID with changed content is quarantined. Reversal references must point to an applied original and may occur once only. Report accepted, ignored and quarantined IDs and ledger effects without mutating the input batch.', {'events':[{'id':'E','sequence':1,'amount':'10'},{'id':'E','sequence':1,'amount':'10'}]}, {'accepted':['E'],'ignored':['E'],'quarantined':[],'net':'10.00'}),
 ('allocate_cost_centers', 'Cost pool allocation with rounding conservation', 'Allocate a cost pool using nonnegative driver weights, independently by pool/currency. Reject missing or zero-sum drivers. Floor shares to cents then distribute residual cents by largest fractional remainder and stable cost-center ID. Verify allocated total equals source total, report exclusions and avoid favorable treatment based on input order.', {'pool':'10.00','drivers':{'A':1,'B':1,'C':1}}, {'A':'3.34','B':'3.33','C':'3.33'}),
 ('resolve_cutoff', 'Purchase and revenue cutoff classifier', 'Classify source records by the documented transfer-of-control or service-completion date, not invoice or payment date. Require evidence IDs and flag contradictory dates. For period boundaries use an explicitly supplied timezone; missing timezone is invalid. Return current-period, next-period and unresolved IDs with independent reasons.', {'start':'2025-01-01','end':'2025-01-31','records':[{'id':'R','control_date':'2025-02-01','invoice_date':'2025-01-30','evidence':'D1'}]}, {'current':[],'next':['R'],'unresolved':[]}),
 ('reconcile_payroll', 'Payroll register-to-ledger reconciliation', 'Reconcile gross pay, employee deductions, employer charges and net pay to journal lines. Keep employee withholding distinct from employer expense. Reject duplicate employee-period rows, net amounts not equal to gross less employee deductions and unexplained ledger differences. Report per-period differences and exception reasons rather than correcting source data silently.', {'gross':'1000','employee_deductions':'200','employer_charges':'100','net_paid':'800','ledger_expense':'1100'}, {'net_difference':'0.00','expense_difference':'0.00','exceptions':[]}),
 ('reconcile_refunds', 'Customer refund entitlement engine', 'Compute refundable balances per original transaction after valid prior refunds and chargebacks, never below zero. A refund cannot exceed the remaining entitlement or change currency. Reject unknown originals, duplicate refund IDs and pending refunds treated as completed. Return remaining entitlement, accepted refunds and rejection reason codes.', {'sales':[{'id':'S','amount':'100','currency':'USD'}],'refunds':[{'id':'R','sale':'S','amount':'30','currency':'USD','status':'completed'}]}, {'remaining':{'S':'70.00'},'accepted':['R'],'rejected':{}}),
 ('aggregate_expense_claims', 'Expense substantiation and duplicate review', 'Validate receipts, business purpose, dates and policy limits. Split mixed personal/business expenses by documented allocation; flag repeated receipt hashes across employees. Meals use the policy percentage, not a hardcoded jurisdiction rate. Return reimbursable and rejected amounts by claim plus duplicate groups, without counting a duplicated receipt twice.', {'meal_percentage':'0.5','claims':[{'id':'C','type':'meal','amount':'100','business_fraction':'1','receipt_hash':'H','purpose':'client meeting'}]}, {'reimbursable':{'C':'50.00'},'duplicates':[]}),
 ('reconcile_subscription_ledger', 'Subscription deferral rollforward', 'Recognize subscription consideration evenly by service day through cutoff and reconcile cash billings to earned and deferred amounts. Credit notes must refer to original subscriptions and reduce only the supported portion. Handle leap years, partially completed periods and cancelled subscriptions. Return per-contract workpapers and an aggregate cash-to-revenue bridge.', {'as_of':'2025-01-15','subscriptions':[{'id':'S','start':'2025-01-01','end':'2025-01-30','cash':'300'}]}, {'S':{'earned':'150.00','deferred':'150.00'}}),
 ('validate_vendor_changes', 'Vendor bank change risk review', 'Compare bank-change requests with independently verified evidence, maker/checker identities, prior values and effective dates. A future verified change must not authorize a present payment. Reject duplicate requests, unverifiable account ownership and maker/checker conflicts. Return effective authorized changes and blocked requests with all reasons.', {'as_of':'2025-01-01','requests':[{'id':'R','effective':'2025-02-01','verified':True,'maker':'A','checker':'B'}]}, {'authorized':[],'blocked':{'R':['future_effective_date']}}),
 ('reconcile_petty_cash', 'Imprest cash reconciliation', 'Reconcile counted cash, substantiated vouchers, IOUs and unreconciled advances to the authorized float. IOUs are receivables, not expense vouchers. Separate shortages from unsupported expense, prevent duplicate voucher IDs and exclude vouchers after cutoff. Return cash shortage, valid replenishment and unsupported items.', {'float':'500','counted':'300','vouchers':[{'id':'V','amount':'150','supported':True}],'ious':'20'}, {'shortage':'30.00','replenishment':'150.00','receivable':'20.00'}),
 ('apply_credit_limits', 'Credit exposure and order release', 'Compute customer exposure from posted open invoices, fulfilled unbilled deliveries and pending orders, net of confirmed unapplied cash. Do not deduct disputed promises to pay. Release orders in priority/date/ID order only when the updated exposure remains within limit. Reject duplicate order IDs and negative credit limits.', {'limit':'100','open_invoices':'60','confirmed_cash':'10','orders':[{'id':'O','amount':'40'}]}, {'released':['O'],'held':[],'final_exposure':'90.00'}),
 ('reconcile_purchase_commitments', 'PO receipt and accrual engine', 'For each PO line, match approved receipts and valid invoices by quantity and price tolerance. Accrue received-but-unbilled quantities only; open undelivered commitments are not accruals. Returns reverse receipts. Block duplicate receipt/invoice IDs and invoices for unsupported quantities. Return accruals, remaining commitments and exception rows.', {'lines':[{'id':'L','ordered':10,'received':8,'invoiced':5,'price':'20'}]}, {'accruals':{'L':'60.00'},'commitments':{'L':'40.00'},'exceptions':[]}),
 ('calculate_covenants', 'Debt covenant test with cure rules', 'Evaluate supplied debt/EBITDA and interest-coverage limits from policy-defined adjustments. Restricted cash is not netted from debt. Missing or nonpositive denominators produce unresolved status, not a pass. Apply cure amounts only when documented and within the stated period. Return ratios, headroom and breach reasons with Decimal precision.', {'debt':'300','unrestricted_cash':'50','ebitda':'100','interest':'20','max_leverage':'3','min_cover':'4'}, {'net_leverage':'2.50','interest_cover':'5.00','status':'pass'}),
 ('validate_chart_mapping', 'Multi-entity chart mapping controls', 'Map source accounts to target accounts by entity and effective date, choosing the most specific applicable rule. Reject overlapping equally specific rules, missing active target accounts and mapping across currencies where forbidden. Conserve debit/credit totals and retain source lineage for every result row.', {'as_of':'2025-01-01','rows':[{'entity':'E','account':'100','amount':'10'}],'rules':[{'entity':'E','source':'100','target':'Cash'}]}, {'mapped':[{'target':'Cash','amount':'10.00'}],'exceptions':[]}),
 ('reconcile_security_deposits', 'Security deposit liability rollforward', 'Separate refundable deposits from revenue, recognize only approved documented forfeitures and match refunds to originals. Interest belongs to the party specified by policy. Reject duplicate events, unsupported forfeiture and refunds above outstanding deposits. Return closing liabilities, recognized forfeitures and unresolved IDs.', {'opening':'100','new_deposits':'50','approved_forfeitures':'20','refunds':'30'}, {'closing_liability':'100.00','revenue':'20.00'}),
 ('build_audit_trail', 'Tamper-evident change lineage validator', 'Validate append-only event sequence, predecessor hashes, actor permissions and before/after continuity using canonical JSON SHA256. Report the first broken link and every unauthorized edit. Exact replay of an event is ignored; conflicting replay is blocked. Do not recompute hashes in a way that silently repairs tampered evidence.', {'events':[],'initial_hash':'GENESIS'}, {'valid':True,'first_broken_link':None,'unauthorized':[]}),
]
CLOSE_THEMES = ['Bank cut-off', 'NSF receipt reversal', 'Duplicate supplier invoice', 'Unbilled services', 'Depreciation posting', 'AR control tie-out', 'Unsupported reconciling item', 'Stale outstanding cheque', 'Deposit in transit', 'Vendor master conflict', 'Payroll accrual', 'Credit memo cut-off', 'Prepaid amortization', 'Cash receipt classification', 'Inventory receipt cut-off', 'Expense versus capitalization', 'Related-party journal review', 'Purchase commitment review', 'Bank-fee omission', 'FX bank-charge review', 'Receivable write-off approval', 'Recurring journal reversal', 'Missing source reference', 'Conflicting vendor statement', 'Post-close receipt evidence', 'Imprest cash exception', 'Journal maker-checker conflict', 'Suspense account clearance', 'Unapproved vendor change', 'Final close handoff']


def coding_cases():
    cases = []
    for index, (name, title, contract, inputs, output) in enumerate(CODING_CONTRACTS):
        prompt = contract + ' Implement Python 3.11 standard library only. Use O(n log n) or better where feasible, stable tie-breakers, explicit validation errors and Decimal for monetary values. Define how malformed records are quarantined. Demonstrate idempotency, input immutability and behavior at the boundaries in your tests.'
        cases.append({'title': title, 'description': prompt, 'instructions': 'Implement solve(data). Keep the signature. Include tests for normal, malformed, duplicate and boundary inputs; explain assumptions. No network or external packages. The public example is only one scenario, not the entire grading contract.', 'marks': 100,
            'metadata': {'case_id': f'coding-{index+1:02d}', 'case_version':1, 'workspace':'coding','language':'python','answer_format':'code', 'starter_code': f'def solve(data):\n    """{title}."""\n    # Implement the contract without mutating data.\n    pass\n',
                         'public_examples':[{'input':inputs,'expected':output}], 'difficulty':'Advanced', 'editorial_review_status':'Independent engineering review pending'},
            'expected_output': {'behavioral_contract': contract, 'required_tests':['public example','missing required field','duplicate source identifier','currency/precision boundary','input reordered','input unchanged','zero/empty case with stated policy'], 'reference_example':{'input':inputs,'expected':output}},
            'grading_config': {'evaluation_mode':'manual_behavioral_review','manual_review_required':True, 'rubric':'Run the supplied test suite in the isolated runner; inspect boundary handling, accuracy, deterministic ordering, validation, complexity and explanatory handoff. No automatic correctness claim from keywords.'}})
    return cases


def accounting_cases():
    cases=[]
    for i, theme in enumerate(CLOSE_THEMES):
        opening = 450000 + i * 4200
        outstanding = 26000 + i * 130
        transit = 18500 + i * 110
        fee = 540 + i * 15
        receipt = 14000 + i * 180
        nsf = 3200 + i * 70
        expected_book = opening - fee + receipt - nsf
        gap = 950 + i * 25 if i % 3 == 0 else 0
        statement = expected_book + outstanding - transit + gap
        accrual = 21000 + i * 550
        depreciation = 9500 + i * 180
        ar_control = 610000 + i * 2000
        ar_subledger = ar_control - 4800 - i * 100
        prepaid = 12000 + i * 240
        fields = {'adjusted_bank_cash': statement - outstanding + transit, 'adjusted_book_cash': expected_book,
                  'unresolved_cash_difference': gap, 'required_ar_control_decrease': ar_control-ar_subledger,
                  'expense_accrual': accrual, 'depreciation_entry': depreciation, 'duplicate_ap_correction': 8800+i*160,
                  'prepaid_expense_recognition': prepaid * 3 / 12, 'net_close_profit_adjustment': money(-accrual-depreciation-prepaid*3/12+8800+i*160)}
        docs=[document('bank','Period-end bank and cash ledger', {'statement_balance':statement,'ledger_cash_before_adjustment':opening,'outstanding_cheques':outstanding,'deposits_in_transit':transit,'unposted_bank_fee':fee,'unposted_customer_receipt':receipt,'unposted_NSF_reversal':nsf}, 'All bank-side timing items are substantiated. Ledger receipts are already in AR. NSF reverses cash to AR. Any remaining difference is unresolved; do not invent a plug.'),
              document('close','Subledgers and close source documents', {'AR_control':ar_control,'verified_AR_subledger':ar_subledger,'supported_unbilled_service_accrual':accrual,'monthly_depreciation':depreciation,'duplicate_vendor_invoice_amount':8800+i*160,'annual_insurance_policy_cost':prepaid,'insurance_coverage':'October 1 through September 30; close is December 31'}, 'The AR difference is a duplicate control posting; decrease AR control and reverse the duplicate sales credit. The supplier invoice is duplicated in AP and expense and must be voided once. Required journal values are gross adjustments; the profit bridge excludes separate bank and AR corrections.'),
              document('controls','Control evidence and reviewer request', {'focus':theme,'unresolved_bank_gap_present':bool(gap),'invoice_approval':'Second duplicate has no distinct goods receipt','journal_approval':'Preparer and reviewer must be independent'}, 'Do not mark the close fully reconciled when evidence leaves a cash gap. Provide journal directions and unresolved follow-up in the reviewer note.')]
        flags=['Duplicate supplier invoice requires reversal','AR control duplicate posting requires correction','Unbilled received service requires accrual']
        if gap: flags.append('Unresolved cash difference requires investigation')
        cases.append(workpaper_task(f'accounting-{i+1:02d}', f'Month-end close · {theme}', fields, {}, docs, flags, [], 'Fictional December accrual-basis close. Every gross journal output is supported by the pack. No tax return or unsupported plug entries. Write the journal directions, evidence IDs and reviewer follow-up.', 'accounting', f'Review {theme.lower()} together with bank reconciliation, AR, AP duplicates, accrual, depreciation and prepaid insurance.'))
    return cases


def spreadsheet_cases():
    original=next(row for row in DEFAULT_ASSESSMENTS if row['id']=='working-capital-model')['task']
    cases=[]
    for i, theme in enumerate(CLOSE_THEMES):
        task=deepcopy(original)
        task['title']=f'FP&A model · {theme}'
        task['metadata']['case_id']=f'spreadsheet-{i+1:02d}'
        task['metadata']['case_version']=1
        task['metadata']['difficulty']='Advanced'
        task['metadata']['editorial_review_status']='Independent finance review pending'
        sheet=task['metadata']['initial_spreadsheet_data']
        # Recompute every answer from a varied operating data set, not a renamed
        # workbook with an unchanged key. Assumptions are explicitly supplied.
        for row in range(3,15):
            for col in 'BCDEFGHIJK':
                sheet[f'{col}{row}']=int(sheet[f'{col}{row}']*(1+i*.013+(row%3)*.002*i))
            sheet[f'L{row}']=max(0,int(sheet[f'L{row}']) + i%4)
        rev=sum(sheet[f'B{r}'] for r in range(3,15)); budget=sum(sheet[f'C{r}'] for r in range(3,15))
        cogs=sum(sheet[f'D{r}'] for r in range(3,15)); opex=sum(sheet[f'F{r}'] for r in range(3,15)); cash=sum(sheet[f'K{r}'] for r in range(3,15))
        gross=rev-cogs; operating=gross-opex
        dso=round(sheet['H14']/rev*365,2); inv=round(sheet['I14']/cogs*365,2); payable=round(sheet['J14']/cogs*365,2)
        qrev=sum(sheet[f'B{r}'] for r in range(12,15)); qbudget=sum(sheet[f'C{r}'] for r in range(12,15))
        values=[rev,budget,rev-budget,round((rev-budget)/budget,4),cogs,gross,round(gross/rev,4),opex,opex-sum(sheet[f'G{r}'] for r in range(3,15)),operating,round(operating/rev,4),dso,inv,payable,round(dso+inv-payable,2),cash,round(cash/rev,4),sum(sheet[f'L{r}'] for r in range(3,15)),qrev,qbudget,round((qrev-qbudget)/qbudget,4),round(rev*(1+float(sheet['N3']))),round(rev/12,2),sum(sheet[f'B{r}']<sheet[f'C{r}'] for r in range(3,15))]
        for check,value in zip(task['grading_config']['checkpoints'], values): check['expected']=value
        task['expected_output']['expected_final_values']={f'B{19+j}':value for j,value in enumerate(values)}
        task['description'] += f' Dataset {i+1:02d}: prepare the model for the {theme.lower()} management review; identify which close evidence would need follow-up before publishing the forecast.'
        cases.append(task)
    return cases


def main():
    target=ROOT/'app/content/practical_assessment_banks.json'
    payload=json.loads(target.read_text(encoding='utf-8'))
    for key,cases in [('invoice-reconciliation-engine',coding_cases()),('month-end-close',accounting_cases()),('working-capital-model',spreadsheet_cases())]:
        payload['banks'][key]={'case_count':len(cases),'difficulty':'Advanced','review_status':'Independent subject-expert review pending','cases':cases}
    target.write_text(json.dumps(payload,indent=2)+'\n',encoding='utf-8')
    print({key:len(bank['cases']) for key,bank in payload['banks'].items()})


if __name__=='__main__': main()
